### PR TITLE
Added "Copy to Clipboard" button to code blocks

### LINKED ISSUE #245: Add "Copy to clipboard" option like in Micronaut docs
Add a "Copy to clipboard" button in the guides like the one existing in the Micronaut documetation that copies the code snippet to the clipboard:

image

### PR DESCRIPTION
**Pull request by burtbeckwith**
Fixes #245

### CODE REVIEW

**Review by ilopmar — CHANGES_REQUESTED** [review]
This changes don't work for me, both the index page and any individual guide page are "black":

image


There is no javascript error in the console, thought.

I've tried with Brave & Firefox.

**Comment by burtbeckwith** [comment]
@ilopmar could you try on another machine? I did the work on Linux and tested in Firefox, but it works fine in Chrome and also in Chrome and Firefox on Mac. The code is from the user guide (multi-language-sample.js and guide.js) - the only change was the element where the button is added, `listingblock` instead of `multi-language-sample` since we only show one language per guide

**Comment by burtbeckwith** [comment]
@ilopmar I see the problem - the page runs differently when you load it with a `file://` url than when it's served from a web server. I use livereload (`cd build/dist && livereload -p 3000`) but any server will work

**Comment by burtbeckwith** [comment]
It should work now, I was using `<script />` but it needs to be `<script></script>`

**Comment by ilopmar** [comment]
Yes, now it works. I've tried serving the content with python (`sudo python3 -m http.server 80 --directory build/dist`) and it didn't work either. Now it also works with you last commit even if I use `file://....`

**Review by ilopmar — APPROVED** [review]

**Pull request merged**
