### PR TITLE
OpenAPI Adoc Guide

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by timyates** [comment]
The native tests don't work.  Switch to a Graal jdk and run `./gradlew :clean :mOAdocBuild --no-build-cache`

```
Test run finished after 111 ms
[         9 containers found      ]
[         0 containers skipped    ]
[         9 containers started    ]
[         0 containers aborted    ]
[         9 containers successful ]
[         0 containers failed     ]
[         8 tests found           ]
[         0 tests skipped         ]
[         8 tests started         ]
[         0 tests aborted         ]
[         5 tests successful      ]
[         3 tests failed          ]
```

**Comment by timyates** [comment]
@sdelamo the fix for Graal is to add:

```
{
  "resources": {
    "includes": [
      {"pattern": "META-INF/swagger/micronaut-guides-1.0.adoc$"}
    ]
  }
}
```

as `resources/META-INF/native-image/io.guide/openapi/resource-config.json`

Is this a bug in the openapi module?

Not sure, as the openapi adoc library is just an annotation processor 🤔

**Comment by sdelamo** [comment]
I think it is an issue in the OpenAPI Module.

**Review by timyates — APPROVED** [review]
As we don't currently run the native tests here this passes 👍

**Comment by sdelamo** [comment]
> As we don't currently run the native tests here this passes 👍

I have added the resource config and a section. Good catch in the review @timyates

**Review by timyates — APPROVED** [review]
Nice 👍

**Pull request merged**
