### PR TITLE
MicroStream persistence guide

### PR DESCRIPTION
**Pull request by timyates**
[skip ci]

Won't work until 3.5.0 is out

To generate the project locally until then:

- publish micronaut-starter to maven local
- change `version.txt` to the published version (3.5.0-SNAPSHOT at time of writing)
- Add `mavenLocal()` to `build.gradle` and `buildSrc/build.gradle`
- Run `./gradlew micronautMicrostreamPersistenceGenerateProjects`
- Open in intellij with `idea build/code/micronaut-microstream-persistence/micronaut-microstream-persistence-gradle-java`
- Open the generated project (Gradle) and add `mavenLocal()` and:
    ```
    annotationProcessor(platform("io.micronaut.microstream:micronaut-microstream-bom:1.0.0-SNAPSHOT"))
    implementation(platform("io.micronaut.microstream:micronaut-microstream-bom:1.0.0-SNAPSHOT"))
    ```

### CODE REVIEW

**Comment by sdelamo** [comment]
I have done some changes. Only to the Java code. I will do to Kotlin and Groovy if you like them. 

To test it locally: 

edit `guides/microanut-microstream-persistence/metatata.json`.  Remove `microstream` feature. 

Run : 


```
./gradlew clean micronautMicrostreamPersistenceBuild --console=plain -x micronautMicrostreamPersistenceRunTestScript
```


Read the HTML guide for Java and Gradle. 


Check the code. Go to: 

`cd build/code/micronaut-microstream-persistence/micronaut-microstream-persistence-gradle-java/` and add the following dependencies: 

```
annotationProcessor("io.micronaut.microstream:micronaut-microstream-annotations:1.0.0-SNAPSHOT")
implementation("io.micronaut.microstream:micronaut-microstream-annotations:1.0.0-SNAPSHOT")
implementation("io.micronaut.microstream:micronaut-microstream:1.0.0-SNAPSHOT")
developmentOnly("io.micronaut.microstream:micronaut-microstream-rest:1.0.0-SNAPSHOT")
```

You mayneed to add `mavenLocal()` and enable rest until [this PR is merged](https://github.com/micronaut-projects/micronaut-microstream/pull/68). 

What do you think @timyates ?

**Comment by timyates** [comment]
Changes look awesome 😎 

Testing the code

**Comment by timyates** [comment]
Code looks good too :shipit:

**Comment by timyates** [comment]
Groovy code LGTM 👍

**Pull request merged**
