### PR TITLE
Remove Reactor from the micronaut-security-jwt-cookie guide

### PR DESCRIPTION
**Pull request by timyates**
This fails as we do not end up on the authFailed page in the Geb test

I have added debug to the test to print the page content when we are expecting to be back at the login page.

The content currently is:

```json
{"_links":{"self":[{"href":"/login","templated":false}]},"_embedded":{"errors":[{"message":"Unknown"}]},"message":"Unknown"}
```

### CODE REVIEW

**Comment by sdelamo** [comment]
I think this unveiled this bug https://github.com/micronaut-projects/micronaut-security/pull/1610

**Comment by sdelamo** [comment]
@timyates can you merge master into this?

**Comment by timyates** [comment]
@sdelamo merged!  Back to just that test failing until Micronaut 4.3.4

**Review by sdelamo — APPROVED** [review]
I bumped up to 4.3.4

**Pull request merged**
