### PR TITLE
Update Guides to Micronaut 4

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
Guides with errors: 

- [x] hotwire-turbo-micronaut-chat
- [x] micronaut-aws-parameter-store
- [x] micronaut-cache
- [x] micronaut-cloud-secrets-azure
- [x] micronaut-cloud-trace-google
- [x] micronaut-cloud-trace-oci
- [x] micronaut-configuration
- [x] micronaut-creating-first-graal-app
- [x] micronaut-data-access-mybatis
- [x] micronaut-data-hibernate-reactive
- [x] micronaut-data-jdbc-repository
- [x] micronaut-data-r2dbc-repository
- [x] micronaut-email-sendgrid
- [x] micronaut-file-download-excel
- [x] micronaut-flyway
- [x] micronaut-graphql
- [x] micronaut-graphql-todo
- [x] micronaut-hibernate-reactive
- [x] micronaut-http-client
- [x] micronaut-java-records
- [x] micronaut-jaxrs-jdbc
- [x] micronaut-jpa-hibernate
- [x] micronaut-kafka/books
- [x] micronaut-kotlin-extension-fns
- [x] micronaut-liquibase
- [x] micronaut-metrics-aws
- [x] micronaut-metrics-oci
- [x] micronaut-metrics
- [x] micronaut-microservices-distributed-tracing-jaeger-opentelemetry
- [x] micronaut-microservices-distributed-tracing-jaeger
- [x] micronaut-microservices-distributed-tracing-zipkin-opentelemetry
- [x] micronaut-microservices-distributed-tracing-zipkin
- [x] micronaut-microservices-services-discover-consul
- [x] micronaut-microservices-services-discover-eureka
- [x] micronaut-microstream-persistence
- [ ] micronaut-mongodb-asynchronous
- [ ] micronaut-mongodb-synchronous
- [x] micronaut-oauth2-auth0
- [x] micronaut-oauth2-client-credentials-auth0
- [x] micronaut-oauth2-client-credentials-cognito
- [x] micronaut-oauth2-cognito
- [x] micronaut-oauth2-github
- [x] micronaut-oauth2-linkedin
- [x] micronaut-oauth2-oidc-google
- [x] micronaut-oauth2-okta
- [x] micronaut-object-storage-gcp
- [x] micronaut-object-storage-oracle-cloud
- [ ] micronaut-oracle-autonomous-db
- [x] micronaut-oracle-email-delivery
- [x] micronaut-oracle-function-http
- [x] micronaut-rabbitmq-rpc
- [x] micronaut-rabbitmq
- [x] micronaut-security-api-key
- [x] micronaut-security-basicauth
- [x] micronaut-security-jwt-cookie
- [x] micronaut-security-jwt
- [x] micronaut-security-keys-jwks
- [x] micronaut-security-session
- [x] micronaut-spring-boot
- [x] micronaut-token-propagation/intermediate-gateway
- [x] micronaut-turbo-native

**Comment by timyates** [comment]
security-keys-jwks still fails, but with

```
Failed to inject value for parameter [configuration] of method [signatureConfiguration] of class: io.micronaut.security.token.jwt.signature.rsa.RSASignatureFactory

Message: Multiple possible bean candidates found: [$SecondarySignatureConfiguration$Definition$Intercepted, $PrimarySignatureConfiguration$Definition$Intercepted]
```

At runtime...  This makes no sense to me, as RSASignatureFactory has an EachBean annotation...  I suspect a bug in core...  I will get more done here, then try and reproduce it

Raised https://github.com/micronaut-projects/micronaut-core/pull/9534

**Comment by timyates** [comment]
GraphQL doesn't work with Serde as we would need to add

```
@SerdeImport(GraphQLRequestBody.class)
@SerdeImport(GraphQLResponseBody.class)
```

**Comment by timyates** [comment]
micronaut kafka is failing due to the KSP/Serde issue and awaitility tries to pull in Groovy 3 for the spock tests 🙄 

As we don't use awaitility in the spock tests, I'm going to try and merge master in to use the language dependent features

**Comment by timyates** [comment]
@alvarosanchez The Micronaut-MicroStream-Persistence guide fails for Maven and Groovy with a weird error...

If you run:

```
./gradlew clean micronautMicrostreamPersistenceBuild
```

Then the `micronaut-microstream-persistence-maven-groovy` tests fail with:

```
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.13.0:generateStubs (default) on project default: Error occurred while calling a method on a Groovy class from classpath.: InvocationTargetException: io/micronaut/inject/processing/ProcessingException: io.micronaut.inject.processing.ProcessingException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

🤔

**Comment by alvarosanchez** [comment]
It is reproducible today in Starter with the MicroStream feature, which incorrectly adds `micronaut-microstream-annotations` in both `compile` and `provided` scopes.

If you just leave it in `provided` it works.

**Comment by timyates** [comment]
micronaut-hibernate-reactive currently fails due to https://github.com/micronaut-projects/micronaut-validation/pull/165

**Comment by timyates** [comment]
The k8s guides are also failing (not on the list)

I'll take a look

**Comment by timyates** [comment]
I have added `skipMavenTests` and `skipGradle` tests to the Oracle Autonomous Database until we get Flyway fixed in Starter to pull flyway-database-oracle when Flyway and oracle are selected as features

**Comment by timyates** [comment]
the `micronaut-oracle-cloud-streaming` seems to show a bug in starter...  We are configuring testResources as using a shared service even though we are not applying the plugin.

I will work on a fix

**Comment by timyates** [comment]
The fix for this is here https://github.com/micronaut-projects/micronaut-starter/pull/1944

It's a bug in 3.9.x as well, so I targetted that for the PR and it will need merging up once released

**Pull request merged**
