### PR TITLE
A class needs to be `Serializable`.

### LINKED ISSUE #666: Cache Guide doesn't mention that class needs to be Serializable

### PR DESCRIPTION
**Pull request by jacekgajek**
Cache Guide didn't mention that class needs to be Serializable

Fix https://github.com/micronaut-projects/micronaut-guides/issues/666

### CODE REVIEW

**Comment by jacekgajek** [comment]
(I've signed the agreement it's just stuck on "pending")

**Comment by sdelamo** [comment]
How can I verify this? I don't think it needed to be Serializable when we wrote the guide. Moreover, the guide has tests.

**Comment by jacekgajek** [comment]
https://github.com/jacekgajek/redis-error-demo
This is actually a showcase for a bug in caching suspending funs, but if you remove `Serializable` then the non-suspending controllers will fail with error
```
 "message": "Internal Server Error: I/O error occurred during serialization: com.example.BarController$Bar"
```

**Comment by jacekgajek** [comment]
Putting this here to prove that I agreed to the CLA
image

**Comment by jacekgajek** [comment]
https://github.com/jacekgajek/redis-error-demo
This is actually a showcase for a bug in caching suspending funs, but if you remove `Serializable` then the non-suspending controllers will fail with error
```
 "message": "Internal Server Error: I/O error occurred during serialization: com.example.BarController$Bar"
```

**Comment by sdelamo** [comment]
> https://github.com/jacekgajek/redis-error-demo This is actually a showcase for a bug in caching suspending funs, but if you remove `Serializable` then the non-suspending controllers will fail with error
> 
> ```
>  "message": "Internal Server Error: I/O error occurred during serialization: com.example.BarController$Bar"
> ```

Is this unrelated to the guide? If it is not related I would like to move it to a different issue. 

For the guide, we have tests. I don't think it is necessary. Am I missing anything?

**Comment by sdelamo** [comment]
Closing this PR, I don't think it needs to be serializable.

**Pull request closed without merging**
