### PR TITLE
Client Generator Guide

### PR DESCRIPTION
**Pull request by timyates**
To see if it runs through CI when it's not a remote branch PR
Original: https://github.com/micronaut-projects/micronaut-guides/pull/816

### CODE REVIEW

**Comment by timyates** [comment]
@andriy-dmytruk Failed one test https://ge.micronaut.io/s/5plecepiwalsw/console-log?task=:micronautOpenapiGeneratorServerRunTestScript

Re-running to see if it's flakey

**Comment by timyates** [comment]
It had to run all the tests before as we changed something in buildSrc, should be quicker now :-D

**Comment by timyates** [comment]
@andriy-dmytruk @sdelamo all green 🥳

**Comment by andriy-dmytruk** [comment]
@timyates Did you change anything or did it just pass?

**Comment by timyates** [comment]
Didn't change a thing, just made it a local pr so it used the secrets

I suspect PRs from forked repos don't have access to secrets

**Comment by andriy-dmytruk** [comment]
@timyates The tests seem to fail for `micronaut-security-basicauth-maven-kotlin` and not OpenAPI guides.
(`java.lang.IllegalStateException: failed to analyze: java.lang.reflect.InvocationTargetException`)
I am not sure what is the reason. Can you take a look at that? 

https://ge.micronaut.io/s/3xu27oodvlmis/console-log#L909

**Comment by timyates** [comment]
@andriy-dmytruk I believe it's this https://github.com/micronaut-projects/micronaut-starter/pull/1208#event-6568443535

I need to see if the other guides now pass as this is in to the snapshot

**Pull request merged**
