### PR TITLE
run only tests for changed guides

### PR DESCRIPTION
**Pull request by sdelamo**
This will allow us to run only the tests for the guides you have changed in the PR. It runs the tests only if your changes are actually a code change. 

I want whole test suite to be run for cron github actions hence the check for the Github workflow name.

### CODE REVIEW

**Comment by ilopmar** [comment]
I don't understand this change. Do you want to run only the tests in a cronjob instead for PRs and when we merge on master?

**Comment by sdelamo** [comment]
If I write a new guide or change an existing guide, I want o run only the tests for that guide not the tests of every guide.

**Comment by ilopmar** [comment]
and what about what you said here?

> I want whole test suite to be run for cron github actions hence the check for the Github workflow name.

**Comment by sdelamo** [comment]
> and what about what you said here?
> 
> > I want whole test suite to be run for cron github actions hence the check for the Github workflow name.

I want to run every tests in the cron job. 

However, when I do a PR and add a new guide or change a guide I want to run only the tests for that guide.

**Comment by sdelamo** [comment]
You can see an example here: 

https://github.com/micronaut-projects/micronaut-guides/runs/2784118085?check_suite_focus=true

**Comment by ilopmar** [comment]
The problem I see with this approach is that we need to go and check if there has been an error or not. For example, the snapshot has been failing for a while for Micronaut 3.0.x https://github.com/micronaut-projects/micronaut-guides/actions/workflows/gradle-snapshot.yml but unless we go there and see what's going on, we don't really now.

I'm also worried about the PRs that upgrade Micronaut version. Will all the test be executed for those PRs?

I think it's safer (and slower) to run all the tests.

**Comment by sdelamo** [comment]
> I'm also worried about the PRs that upgrade Micronaut version. Will all the test be executed for those PRs?

I have done a commit to ensure in PRs which modifies `version.txt` or `pom.xml` is changed every tests is executed.

**Comment by sdelamo** [comment]
> The problem I see with this approach is that we need to go and check if there has been an error or not. For example, the snapshot has been failing for a while for Micronaut 3.0.x https://github.com/micronaut-projects/micronaut-guides/actions/workflows/gradle-snapshot.yml but unless we go there and see what's going on, we don't really now.

I think this PR does not affect this. We should to investigate failures of crons jobs.

**Comment by ilopmar** [comment]
> > The problem I see with this approach is that we need to go and check if there has been an error or not. For example, the snapshot has been failing for a while for Micronaut 3.0.x [micronaut-projects/micronaut-guides/actions/workflows/gradle-snapshot.yml](https://github.com/micronaut-projects/micronaut-guides/actions/workflows/gradle-snapshot.yml) but unless we go there and see what's going on, we don't really now.
> 
> I think this PR does not affect this. We should to investigate failures of crons jobs.

No, this PR doesn't affect it. It's been failing for a few weeks now. 

Last run failed because of missing `@Nonnull` dependency (I'll do the change and replace everything to use Micronaut `@NotNull` and `@NonNull`).

In the run from [two weeks ago](https://github.com/micronaut-projects/micronaut-guides/runs/2703536569?check_suite_focus=true#step:7:1512), these guides failed: 
```
  micronaut-database-authentication-provider-gradle-groovy
  micronaut-oauth2-cognito-gradle-java
  micronaut-oauth2-cognito-maven-java
  micronaut-oauth2-oidc-google-gradle-java
  micronaut-oauth2-oidc-google-maven-java
  micronaut-oauth2-linkedin-gradle-java
  micronaut-oauth2-linkedin-maven-java
  micronaut-oauth2-github-gradle-java
  micronaut-oauth2-github-maven-java
  micronaut-oauth2-okta-gradle-java
  micronaut-oauth2-okta-maven-java
```

**Review by ilopmar — APPROVED** [review]

**Pull request merged**
