### PR TITLE
Replace h2 with real database for testing guide

### PR DESCRIPTION
**Pull request by sdelamo**
Port of Spring Boot Guide https://testcontainers.com/guides/replace-h2-with-real-database-for-testing/

I added a Test Resources section to show how you can simplify testing.

To generate guide locally:

./gradlew replaceH2WithRealDatabaseForTestingBuild

Open HTML locally:

open build/dist/index.html

Code available:

build/code/replace-h2-with-real-database-for-testing

### CODE REVIEW

**Comment by sdelamo** [comment]
@sivaprasadreddy do you want to review it?

**Review by timyates — APPROVED** [review]
Should we rename the `jdbc` project `jdbc-testresources`?

And `postgresqltestresources` `postgresql-testresources`?

**Comment by sdelamo** [comment]
> Should we rename the `jdbc` project `jdbc-testresources`?
> 
> And `postgresqltestresources` `postgresql-testresources`?

Not against renaming them.

**Comment by sdelamo** [comment]
@sivaprasadreddy could you review this guide?

**Pull request merged**
