### PR TITLE
Revert exclusions for Micronaut 4.1.1

### PR DESCRIPTION
**Pull request by sdelamo**
This reverts commit 6caf28ae009c37827acb2935a74987e437dbb0b1.

### CODE REVIEW

**Comment by sdelamo** [comment]
@timyates lets keep an eye on this.

**Comment by timyates** [comment]
@sdelamo All the exclusions could be reverted apart from the Oracle Object Storage one

@alvarosanchez @yawkat Any idea what's missing there? The issue was [discovered here on the 4.1.1 update for guides](https://github.com/micronaut-projects/micronaut-guides/pull/1328#issuecomment-1720816931).

There's a class missing for Maven (works with Gradle)

https://ge.micronaut.io/s/bnrv5tspafunw/console-log?page=5#L4833

**Comment by yawkat** [comment]
it means theres some version conflict. that class was added in oci sdk 3.24.0

**Comment by timyates** [comment]
Ahhh, so we need to exclude something from the path for something?

**Review by timyates — APPROVED** [review]

**Comment by timyates** [comment]
@alvarosanchez So I think it's caused by `io.micronaut.oraclecloud:micronaut-oraclecloud-bmc-objectstorage:3.0.4` pulling  in two versions of the oci classes, 3.25.1 and 3.15.0

And there are new classes in 3.25.1 which are missing in 3.15.0

I'm not sure where they come from...are they imported in from a different project in settings.gradle?

**Comment by alvarosanchez** [comment]
That was fixed by https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/709, but seems unreleased

**Comment by timyates** [comment]
I'll release 3.0.5, and get it into platform for 4.1.3

**Comment by timyates** [comment]
Raised https://github.com/micronaut-projects/micronaut-guides/pull/1352 to re-enable maven once 4.1.3 is out

**Comment by sdelamo** [comment]
I will release 4.1.3 tomorrow.

**Pull request merged**
