### PR TITLE
update handler screenshot (Java 11 -> 17)

### PR DESCRIPTION
**Pull request by deki**
The screenshot describing the Lambda handler config was outdated.

### CODE REVIEW

**Review by sdelamo — CHANGES_REQUESTED** [review]
Thanks. However, `MicronautLambdaHandler` is deprecated. It should be `io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyRequestEventFunction` instead

**Comment by sdelamo** [comment]
@deki you need to sign the CLA.

**Comment by deki** [comment]
CLA signed. Then it looks like additional changes are required as `MicronautLambdaHandler` is referenced everywhere in the docs.

**Comment by deki** [comment]
Updated it to `ApiGatewayProxyRequestEventFunction`. 

Where do you plan to mention `ApplicationLoadBalancerFunction` and `APIGatewayV2HTTPEventFunction`? On the same page or as separate guides?

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
> Where do you plan to mention `ApplicationLoadBalancerFunction` and `APIGatewayV2HTTPEventFunction`? On the same page or as separate guides?

We should create a common snippet and mention the different handler options in every guide.

**Review by sdelamo — APPROVED** [review]
Thanks for your contributor. Appreciated @deki

**Pull request merged**
