### PR TITLE
Micronaut 4.1.1

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
`  micronaut-jaxrs-jdbc-maven-java` failed. @timyates can you check it?

**Comment by timyates** [comment]
Looks like classpath issues with maven and jaxrs annotation processing..

It's fixed if we change

```
            <path>
              <groupId>io.micronaut.jaxrs</groupId>
              <artifactId>micronaut-jaxrs-processor</artifactId>
              <version>${micronaut.jaxrs.version}</version>
            </path>
```

to 

```
            <path>
              <groupId>io.micronaut.jaxrs</groupId>
              <artifactId>micronaut-jaxrs-processor</artifactId>
              <version>${micronaut.jaxrs.version}</version>
              <exclusions>
                <exclusion>
                  <groupId>io.micronaut</groupId>
                  <artifactId>micronaut-inject</artifactId>
                </exclusion>
              </exclusions>
            </path>
```

To exclude a different version of micronaut-inject being pulled in with the jaxrs processor...

I'll look for where this needs to be fixed...

**Comment by timyates** [comment]
@sdelamo I've excluded Maven on that guide until the fix in https://github.com/micronaut-projects/micronaut-starter/pull/2050 is released

**Comment by sdelamo** [comment]
`micronautMetricsAwsRunTestScript` failed :-(

**Comment by timyates** [comment]
@alvarosanchez Can you see what the problem might be with `micronautMetricsAwsRunTestScript`?

Maven/Java build is failing with

```
Caused by: java.lang.ClassNotFoundException: io.micronaut.core.beans.BeanIntrospection$Builder
    at java.net.URLClassLoader.findClass (URLClassLoader.java:445)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:587)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:520)
    at io.micronaut.validation.validator.constraints.$InternalConstraintValidators$IntrospectionRef.load (Unknown Source)
    at io.micronaut.core.beans.DefaultBeanIntrospector.lambda$findIntrospection$0 (DefaultBeanIntrospector.java:95)
    at java.util.Optional.map (Optional.java:260)
    at io.micronaut.core.beans.DefaultBeanIntrospector.findIntrospection (DefaultBeanIntrospector.java:91)
    at io.micronaut.core.beans.BeanWrapper.findWrapper (BeanWrapper.java:240)
    at io.micronaut.validation.validator.constraints.InternalConstraintValidators.getConstraintValidators (InternalConstraintValidators.java:471)
    at io.micronaut.validation.validator.constraints.DefaultConstraintValidators.<init> (DefaultConstraintValidators.java:80)
    at io.micronaut.validation.validator.constraints.DefaultConstraintValidators.<init> (DefaultConstraintValidators.java:69)
    at io.micronaut.validation.validator.DefaultAnnotatedElementValidator$LocalConstraintValidators.<init> (DefaultAnnotatedElementValidator.java:54)
    at io.micronaut.validation.validator.DefaultAnnotatedElementValidator.<init> (DefaultAnnotatedElementValidator.java:48)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0 (Native Method)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstanceWithCaller (Constructor.java:499)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:480)
    at io.micronaut.core.io.service.DefaultServiceDefinition.lambda$load$0 (DefaultServiceDefinition.java:74)
    at java.util.Optional.map (Optional.java:260)
    at io.micronaut.core.io.service.DefaultServiceDefinition.load (DefaultServiceDefinition.java:72)
    at io.micronaut.core.io.service.SoftServiceLoader.firstAvailable (SoftServiceLoader.java:138)
```

It works again if I add

```
            <path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-core</artifactId>
              <version>${micronaut.core.version}</version>
            </path>
```

To the maven compiler plugin annotationProcessorPaths...

Is this the right route?  Why is it only happening now?

**Comment by timyates** [comment]
Hope this fixes the Maven annotation processing for metrics

https://github.com/micronaut-projects/micronaut-starter/pull/2052

skipping maven tests and moving on for now

**Comment by timyates** [comment]
And this should fix the tracing guides which I had to exclude from Maven testing

https://github.com/micronaut-projects/micronaut-starter/pull/2053

**Comment by timyates** [comment]
Objectstorage failing now @alvarosanchez 

https://github.com/micronaut-projects/micronaut-guides/actions/runs/6188847138/job/16801682957#step:5:1578

Looks different... Any ideas?

**Comment by timyates** [comment]
I can get it to compile if I add 

```
    <dependency>
      <groupId>com.oracle.oci.sdk</groupId>
      <artifactId>oci-java-sdk-common</artifactId>
      <version>3.25.1</version>
    </dependency>
```

To the generated POM...

It looks like the micronaut-oraclecloud-common module has an old version in the pom 🙄 

https://search.maven.org/artifact/io.micronaut.oraclecloud/micronaut-oraclecloud-common/3.0.4/jar

```
      <dependency>
        <groupId>com.oracle.oci.sdk</groupId>
        <artifactId>oci-java-sdk-bom</artifactId>
        <version>3.15.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

I think this should be 3.25.1 ...  Investigating...

**Comment by alvarosanchez** [comment]
Pinging @yawkat for the OCI SDK issue

**Comment by timyates** [comment]
I'm going to ignore the maven tests for micronaut-object-storage-oracle-cloud for now.  We see the same thing in [the Gradle build](https://scans.gradle.com/s/xtqeiuupvuv2q/dependencies?focusedDependency=WzAsMSw5NyxbMCwxLFs2LDkyLDk3XV1d&toggled=W1swXSxbMCwxXSxbMCwxLFsyXV0sWzAsMSxbNl1dLFswLDEsWzYsOTNdXSxbMCwxLFs2LDkyXV0sWzAsMSxbNiw5NF1dXQ) but Gradle makes an intelligent version choice 🐘💕  😜

**Comment by timyates** [comment]
And now `micronaut-spring-boot-maven-java` 😭. -- passes locally of course 🙄

**Comment by timyates** [comment]
Excluded spring-boot/maven think https://github.com/micronaut-projects/micronaut-starter/pull/2056 fixes it...

**Pull request merged**
