### PR TITLE
guide: Lambda Java Runtime RequestStreamHandler

### PR DESCRIPTION
**Pull request by sdelamo**
2 guides in here

```
./gradlew clean mSFALRSHGBuild mSFALRSHBuild --no-build-cache
```

### CODE REVIEW

**Review by timyates — APPROVED** [review]

**Comment by sdelamo** [comment]
@timyates I added a GraalVM guide for Micronaut StreamRequestHandler which was fixed in Micronaut Framework 4.2.3. Can you re-review?

**Review by timyates — APPROVED** [review]
@sdelamo I pushed some updates, please check they're ok 👍

**Comment by sdelamo** [comment]
I don't know why the maven build is failing. It seems not be picking the latest version from Micronaut  AWS.

**Comment by timyates** [comment]
Both maven and gradle seem to be failing...  But just for the graal guide

```
 Projects with errors:
  micronaut-serverless-function-aws-lambda-request-stream-handler-graalvm-gradle-java
  micronaut-serverless-function-aws-lambda-request-stream-handler-graalvm-maven-java
```

**Comment by timyates** [comment]
Ahhh, I think it's missing the `"aws-lambda-custom-runtime"` feature

**Review by graemerocher — APPROVED** [review]

**Pull request merged**
