### PR TITLE
Guide alternate styling

### PR DESCRIPTION
**Pull request by JasonTypesCodes**
Alternate styling options for the guide lists

image

image (1)

### CODE REVIEW

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
Once we approve this PR, we will get rid of the guides index in wordpress.

**Review by timyates — APPROVED** [review]
On small screens, the blue title box goes a bit big?

image

If we want to reduce it's height, we can add something like:

```css
@media (max-width: 767.98px) {
    .grid-item:before {
        padding-top: 40%;
    }
}
```

To `guide.css` which would change it to

image

Or, we could leave it as is if that is preferred?

**Comment by sdelamo** [comment]
please, apply the fix @timyates  

> ```css
> @media (max-width: 767.98px) {
>     .grid-item:before {
>         padding-top: 40%;
>     }
> }
> ```

**Comment by timyates** [comment]
@sdelamo done 👍

**Pull request merged**
