### PR TITLE
build: Micronaut 3.6.3

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
@timyates can you investigate the failure?

**Comment by timyates** [comment]
Failure passes locally... rerunning to see

**Comment by timyates** [comment]
@sdelamo I think this is paralleism and Test Resources...

Should I turn off the parallel execution?

But without the "shut down resources" that was reverted, I'm not sure it will work...

**Comment by timyates** [comment]
My suggestion is to:

1. Turn off parallelism in the RunTestScript task for now
1. Re-instate the "shut down test resources" but hide the output so people don't think it's failing the scripts

**Comment by timyates** [comment]
🎉

**Pull request merged**
