### PR TITLE
build: Micronaut Framework 3.9.1

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by timyates** [comment]
I think this is due to https://github.com/micronaut-projects/micronaut-starter/pull/1636 I need to dig in...

**Comment by sdelamo** [comment]
@timyates can you check `micronautCloudTraceGoogle`? It fails.

**Comment by timyates** [comment]
@sdelamo tracing guide was broken by micronaut-tracing 4.5.0 which contains

https://github.com/micronaut-projects/micronaut-tracing/commit/598e16172a1eba6ceffee8e7369d342023b4d546#diff-c5a64512cbe71367881cbad055e952e68307bf2cc8ec7fadc9366dc9eb2f65fe

It's a breaking change, as the package names for `@SpanAttribute` and `@WithSpan` have changed from 

```
import io.opentelemetry.extension.annotations.SpanAttribute;
import io.opentelemetry.extension.annotations.WithSpan;
```

to

```
import io.opentelemetry.instrumentation.annotations.SpanAttribute;
import io.opentelemetry.instrumentation.annotations.WithSpan;
```

And we use these in the guide source

**Comment by sdelamo** [comment]
> @sdelamo tracing guide was broken by micronaut-tracing 4.5.0 which contains
> 
> [micronaut-projects/micronaut-tracing@598e161#diff-c5a64512cbe71367881cbad055e952e68307bf2cc8ec7fadc9366dc9eb2f65fe](https://github.com/micronaut-projects/micronaut-tracing/commit/598e16172a1eba6ceffee8e7369d342023b4d546#diff-c5a64512cbe71367881cbad055e952e68307bf2cc8ec7fadc9366dc9eb2f65fe)
> 
> It's a breaking change, as the package names for `@SpanAttribute` and `@WithSpan` have changed from
> 
> ```
> import io.opentelemetry.extension.annotations.SpanAttribute;
> import io.opentelemetry.extension.annotations.WithSpan;
> ```
> 
> to
> 
> ```
> import io.opentelemetry.instrumentation.annotations.SpanAttribute;
> import io.opentelemetry.instrumentation.annotations.WithSpan;
> ```
> 
> And we use these in the guide source

Please, update the guide for now and create an issue in tracing module about the breaking change

**Pull request merged**
